<a href="https://colab.research.google.com/github/soundarya1992/My-Projects/blob/master/santander_customer_satisfaction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive 
drive.mount('/content/drive')

#/content/drive/My Drive/Santander/santander-customer-satisfaction.zip

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
%cd /content/drive/My\ Drive/Santander

/content/drive/My Drive/Santander


In [0]:
from zipfile import ZipFile
with ZipFile('santander-customer-satisfaction.zip', 'r') as zip: 
  zip.extractall() 
  #zip.extract('Santander/santander-customer-satisfaction.zip/train.csv')

In [0]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
import xgboost as xgb
import os

In [0]:
train = pd.read_csv('train.csv')

In [0]:
test = pd.read_csv('test.csv')

In [0]:
train.head()
test.head()

ID  var3  var15  ...  saldo_medio_var44_ult1  saldo_medio_var44_ult3      var38
0   2     2     32  ...                     0.0                     0.0   40532.10
1   5     2     35  ...                     0.0                     0.0   45486.72
2   6     2     23  ...                     0.0                     0.0   46993.95
3   7     2     24  ...                     0.0                     0.0  187898.61
4   9     2     23  ...                     0.0                     0.0   73649.73

[5 rows x 370 columns]

In [0]:
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75818 entries, 0 to 75817
Columns: 370 entries, ID to var38
dtypes: float64(110), int64(260)
memory usage: 214.0 MB
None


In [0]:
example = train['var3'].value_counts(10, ascending = False)
example.to_csv('check.csv')

In [0]:
train = train.replace(-999999,2)
train.loc[train.var3==-999999].shape

(0, 371)

In [0]:
train = train.loc[:, (train != train.iloc[0]).any()] 

In [0]:
print(train.shape)

(76020, 337)


In [0]:
X = train.iloc[:,:-1]
y = train.TARGET

In [0]:
print(X.shape)

(76020, 336)


In [0]:
X.drop(['ID'], axis=1)

var3  var15  ...  saldo_medio_var44_ult3          var38
0         2     23  ...                     0.0   39205.170000
1         2     34  ...                     0.0   49278.030000
2         2     23  ...                     0.0   67333.770000
3         2     37  ...                     0.0   64007.970000
4         2     39  ...                     0.0  117310.979016
...     ...    ...  ...                     ...            ...
76015     2     48  ...                     0.0   60926.490000
76016     2     39  ...                     0.0  118634.520000
76017     2     23  ...                     0.0   74028.150000
76018     2     25  ...                     0.0   84278.160000
76019     2     46  ...                     0.0  117310.979016

[76020 rows x 335 columns]

In [0]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 123)

In [0]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60816, 336)
(15204, 336)
(60816,)
(15204,)


In [0]:
xgb_class = xgb.XGBClassifier(n_estimators = 75)
xgb_class.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=75, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
preds_class = xgb_class.predict(x_train)

In [0]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [0]:
cm = confusion_matrix(y_train, preds_class)

In [0]:
print(cm)

[[58421     2]
 [ 2391     2]]


In [0]:
print('accuracy score: ', accuracy_score(y_train, preds_class))

accuracy score:  0.960651802157327


In [0]:
print('F1 Score: ', f1_score(y_train, preds_class))

F1 Score:  0.0016687526074259493


In [0]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(x_train, y_train)
X_train_res = pd.DataFrame(X_train_res, columns=x_train.columns)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [0]:
print(X_train_res.shape)
print(y_train_res.shape)

(116846, 336)
(116846,)


In [0]:
print(y_train.value_counts())

0    58423
1     2393
Name: TARGET, dtype: int64


In [0]:
np.unique(y_train_res, return_counts=True)

(array([0, 1]), array([58423, 58423]))

In [0]:
xgb_smote = xgb.XGBClassifier(n_estimators = 100)
xgb_smote.fit(X_train_res, y_train_res)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
preds_class_xgb = xgb_smote.predict(X_train_res)

In [0]:
cm_xgb_smote = confusion_matrix(y_train_res, preds_class_xgb)
acc_score = accuracy_score(y_train_res, preds_class_xgb)
f1_score_xgb_smote = f1_score(y_train_res, preds_class_xgb)
print(cm_xgb_smote)
print(acc_score)
print(f1_score_xgb_smote)

[[54524  3899]
 [ 3126 55297]]
0.9398781301884532
0.9402732551713583


In [0]:
X_test_res.info()
#np.unique(y_test_res, return_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29178 entries, 0 to 29177
Columns: 336 entries, ID to var38
dtypes: float64(336)
memory usage: 74.8 MB


In [0]:
X_test_res, y_test_res = sm.fit_sample(x_test, y_test)
X_test_res = pd.DataFrame(X_test_res, columns=x_test.columns)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [0]:
preds_class_xgb_test = xgb_smote.predict(X_test_res)

In [0]:
cm_xgb_smote_test = confusion_matrix(y_test_res, preds_class_xgb_test)
acc_score_xgb_smote_test = accuracy_score(y_test_res, preds_class_xgb_test)
f1_score_xgb_smote_test = f1_score(y_test_res, preds_class_xgb_test)

print('confusion matrix for test data is :', cm_xgb_smote_test)
print('overall accuracy for the test data is:', acc_score_xgb_smote_test)
print('overall f1 score for the test data is:', f1_score_xgb_smote_test)

confusion matrix for test data is : [[13578  1011]
 [  799 13790]]
overall accuracy for the test data is: 0.9379669614092809
overall f1 score for the test data is: 0.93841442667574


In [0]:
test.head()

ID  var3  var15  ...  saldo_medio_var44_ult1  saldo_medio_var44_ult3      var38
0   2     2     32  ...                     0.0                     0.0   40532.10
1   5     2     35  ...                     0.0                     0.0   45486.72
2   6     2     23  ...                     0.0                     0.0   46993.95
3   7     2     24  ...                     0.0                     0.0  187898.61
4   9     2     23  ...                     0.0                     0.0   73649.73

[5 rows x 370 columns]

In [0]:
test = test.replace(-999999,2)
test.loc[test.var3==-999999].shape

(0, 370)

In [0]:
test_df = test[X.columns]

In [0]:
test_df.head()

ID  var3  var15  ...  saldo_medio_var44_ult1  saldo_medio_var44_ult3      var38
0   2     2     32  ...                     0.0                     0.0   40532.10
1   5     2     35  ...                     0.0                     0.0   45486.72
2   6     2     23  ...                     0.0                     0.0   46993.95
3   7     2     24  ...                     0.0                     0.0  187898.61
4   9     2     23  ...                     0.0                     0.0   73649.73

[5 rows x 336 columns]

In [0]:
submit_predict = xgb_smote.predict(test_df)

In [0]:
test_df['score'] = submit_predict

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
test_df.head()

ID  var3  var15  ...  saldo_medio_var44_ult3      var38  score
0   2     2     32  ...                     0.0   40532.10      0
1   5     2     35  ...                     0.0   45486.72      0
2   6     2     23  ...                     0.0   46993.95      0
3   7     2     24  ...                     0.0  187898.61      0
4   9     2     23  ...                     0.0   73649.73      0

[5 rows x 337 columns]

In [0]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [0]:
standardizedData = StandardScaler().fit_transform(X_train_res)
standardizedData = pd.DataFrame(standardizedData, columns = X_train_res.columns)

pca = PCA(n_components=2)

principalComponents = pca.fit_transform(X = standardizedData)
#principalComponents = pd.DataFrame(principalComponents, columns = X_train_res.columns)
principalDf_train = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

# to get how much variance was retained
print(pca.explained_variance_ratio_.sum())

0.13585011540282338


In [0]:
xgb_pca = xgb.XGBClassifier(n_estimators = 100)
xgb_pca.fit(principalDf_train, y_train_res)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
pred_xgb_pca_train = xgb_pca.predict(principalDf_train)


In [0]:
print('Acc for train pca xgb', accuracy_score(y_train_res,pred_xgb_pca_train))
print('f1 for train pca xgb', f1_score(y_train_res,pred_xgb_pca_train))

Acc for train pca xgb 0.7736336716704038
f1 for train pca xgb 0.7628865979381443


In [0]:
standardizedData_test = StandardScaler().fit_transform(X_test_res)
standardizedData_test = pd.DataFrame(standardizedData_test, columns = X_test_res.columns)

pca_test = PCA(n_components=2)

principalComponents_test = pca_test.fit_transform(X = standardizedData_test)
#principalComponents = pd.DataFrame(principalComponents, columns = X_train_res.columns)
principalDf_test = pd.DataFrame(data = principalComponents_test
             , columns = ['principal component 1', 'principal component 2'])

# to get how much variance was retained
print(pca_test.explained_variance_ratio_.sum())

0.16703839513626065


In [0]:
pred_xgb_pca_test = xgb_pca.predict(principalDf_test)

In [0]:
print('Acc for train pca xgb', accuracy_score(y_test_res,pred_xgb_pca_test))
print('f1 for train pca xgb', f1_score(y_test_res,pred_xgb_pca_test))

Acc for train pca xgb 0.5721776681061074
f1 for train pca xgb 0.6419823902257148


In [0]:
#test_df.to_csv('final.csv')